version: '3'

services:
  bitwarden:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    image: bitwardenrs/server
    volumes:
      - ${BITWARDEN_DATA_PATH}:/data
      - ${BITWARDEN_SSL_PATH}:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      SSL:
      SIGNUPS_ALLOWED: true
      ADMIN_TOKEN: ${ADMIN_PASS}
      SSLCERT: ${BITWARDEN_SSL_CERTIFICATE}
      SSLKEY: ${BITWARDEN_SSL_KEY}

networks:
    default:
       external:
         name: ${NETWORK}
